#!/usr/bin/perl -w

# upload files to trainingstagebuch.org

use warnings;
use strict;
use TtbOrg;
use Getopt::Long;
use Data::Dumper;

my $needhelp;
my $wanthelp;

my $user;
my $pass;
my $delay = 120;
my $sport;

GetOptions(
	"delay=i"	=> \$delay,
	"help!"		=> \$wanthelp,
	"pass=s"	=> \$pass,
	"sport=i"	=> \$sport,
	"user=s"	=> \$user,
) or $needhelp ++;

if( $wanthelp ){
	print "usage: $0 [options] <file1> ...
upload files to trainingstagebuch.org
options:
 --delay=<sec>   delay between file uploads
 --help          this cruft
 --pass=<pwd>    ttb.org password
 --sport=<id>    sport ID to set
 --user=<login>  ttb.org user id
";
	exit 0;
}

$user ||= prompt_user( "Login" );
$pass ||= prompt_user( "Password" );

if( ! $user ){
	$needhelp++;
	print STDERR "missing user name\n";
}

if( ! $pass ){
	$needhelp++;
	print STDERR "missing password\n";
}

if( $needhelp ){
	print STDERR "please use $0 --help for usage info\n";
	exit 1;
}


my $ttb = TtbOrg->new({
	user	=> $user,
	pass	=> $pass,
});

my $uploaded;
foreach my $f ( @ARGV ){
	my $type = ($f =~ /\.([^.]+)$/)[0];

	if( $uploaded && $delay > 0 ){
		print "delaying next upload ($delay)\n";
		sleep( $delay );
	}

	{ local $|=1; print "uploading $f ..."; }
	my $id = $ttb->file_upload( $f, $type );
	print " $id\n";

	if( defined $sport ){
		#my $ret = $ttb->workout_set( $id, [ 'sport-id' => $sport ] );
	}

	$uploaded++;
}

#print Dumper($r);

# all done
exit 1;

sub prompt_user {
	my( $prompt ) = @_;

	{ local $|=1; print $prompt, ": "; }
	my $resp = <STDIN>;
	chomp $resp;
	$resp;
}

